from collections import OrderedDict

HOUSE_STATUS = ('待出租', '已预约', '已签约')
REPAIR_TYPES = ('水电', '门锁', '管道', '家电', '其他')
USER_ROLES = ('房东', '租客', '物业人员')

# 工单生命周期：提交后待响应，物业接单后处理中，处理完成后已完成。
REPAIR_STATUS_PENDING = '待响应'
REPAIR_STATUS_PROCESSING = '处理中'
REPAIR_STATUS_COMPLETED = '已完成'
REPAIR_STATUS = (REPAIR_STATUS_PENDING, REPAIR_STATUS_PROCESSING, REPAIR_STATUS_COMPLETED)

# 分级响应时限（秒）：水电、门锁 30 分钟；管道、家电、其他 4 小时。
REPAIR_SLA_FAST_MINUTES = 30
REPAIR_SLA_NORMAL_MINUTES = 240
RESPONSE_DEADLINE_MINUTES = OrderedDict([
    ('水电', REPAIR_SLA_FAST_MINUTES),
    ('门锁', REPAIR_SLA_FAST_MINUTES),
    ('管道', REPAIR_SLA_NORMAL_MINUTES),
    ('家电', REPAIR_SLA_NORMAL_MINUTES),
    ('其他', REPAIR_SLA_NORMAL_MINUTES),
])

# 工单动态类型。
REPAIR_EVENT_SUBMIT = '提交'
REPAIR_EVENT_ACCEPT = '接单'
REPAIR_EVENT_ESCALATE = '升级'
REPAIR_EVENT_COMPLETE = '完成'
REPAIR_EVENT_TYPES = (
    REPAIR_EVENT_SUBMIT,
    REPAIR_EVENT_ACCEPT,
    REPAIR_EVENT_ESCALATE,
    REPAIR_EVENT_COMPLETE,
)
