ERROR_CODES = {
    'PROPERTY_NOT_FOUND': 'PROPERTY_NOT_FOUND',
    'BOOKING_CONFLICT': 'BOOKING_CONFLICT',
    'REPAIR_INVALID': 'REPAIR_INVALID',
    'REPAIR_TICKET_NOT_FOUND': 'REPAIR_TICKET_NOT_FOUND',
    'REPAIR_STAFF_NOT_FOUND': 'REPAIR_STAFF_NOT_FOUND',
    'REPAIR_STAFF_NOT_ASSIGNED': 'REPAIR_STAFF_NOT_ASSIGNED',
    'REPAIR_ALREADY_ACCEPTED': 'REPAIR_ALREADY_ACCEPTED',
    'REPAIR_NOT_OVERDUE': 'REPAIR_NOT_OVERDUE',
    'REPAIR_ALREADY_ESCALATED': 'REPAIR_ALREADY_ESCALATED',
    'REPAIR_NO_AVAILABLE_STAFF': 'REPAIR_NO_AVAILABLE_STAFF',
    'REPAIR_ALREADY_COMPLETED': 'REPAIR_ALREADY_COMPLETED',
}

ERROR_MESSAGES = {
    'REPAIR_INVALID': '报修信息不合法',
    'REPAIR_TICKET_NOT_FOUND': '报修工单不存在',
    'REPAIR_STAFF_NOT_FOUND': '物业人员不存在',
    'REPAIR_STAFF_NOT_ASSIGNED': '该工单已指派给其他物业人员',
    'REPAIR_ALREADY_ACCEPTED': '工单已被接单，请勿重复操作',
    'REPAIR_NOT_OVERDUE': '工单尚未超时，不能升级',
    'REPAIR_ALREADY_ESCALATED': '工单已升级过，且超时工单只能升级一次',
    'REPAIR_NO_AVAILABLE_STAFF': '暂无可承接工单的物业人员',
    'REPAIR_ALREADY_COMPLETED': '工单已完成',
}
