ERROR_CODES = {
    'PROPERTY_NOT_FOUND': 'PROPERTY_NOT_FOUND',
    'BOOKING_CONFLICT': 'BOOKING_CONFLICT',
    'REPAIR_INVALID': 'REPAIR_INVALID',
    'REPAIR_TICKET_NOT_FOUND': 'REPAIR_TICKET_NOT_FOUND',
    'REPAIR_STAFF_NOT_FOUND': 'REPAIR_STAFF_NOT_FOUND',
    'REPAIR_ALREADY_RESPONDED': 'REPAIR_ALREADY_RESPONDED',
    'REPAIR_TICKET_NOT_PENDING': 'REPAIR_TICKET_NOT_PENDING',
    'REPAIR_ALREADY_ESCALATED': 'REPAIR_ALREADY_ESCALATED',
    'REPAIR_NOT_OVERDUE': 'REPAIR_NOT_OVERDUE',
    'REPAIR_NO_STAFF_AVAILABLE': 'REPAIR_NO_STAFF_AVAILABLE',
    'REPAIR_ALREADY_COMPLETED': 'REPAIR_ALREADY_COMPLETED',
    'REPAIR_NOT_ACCEPTED': 'REPAIR_NOT_ACCEPTED',
}

ERROR_MESSAGES = {
    'PROPERTY_NOT_FOUND': '房源不存在',
    'BOOKING_CONFLICT': '看房时间冲突',
    'REPAIR_INVALID': '报修信息有误',
    'REPAIR_TICKET_NOT_FOUND': '报修工单不存在',
    'REPAIR_STAFF_NOT_FOUND': '物业人员不存在',
    'REPAIR_ALREADY_RESPONDED': '工单已被接单，不能重复接单',
    'REPAIR_TICKET_NOT_PENDING': '工单不在待响应状态，无法升级',
    'REPAIR_ALREADY_ESCALATED': '工单已升级过，只能升级一次',
    'REPAIR_NOT_OVERDUE': '工单尚未超过响应时限，不能升级',
    'REPAIR_NO_STAFF_AVAILABLE': '没有可转派的物业人员',
    'REPAIR_ALREADY_COMPLETED': '工单已完成',
    'REPAIR_NOT_ACCEPTED': '工单尚未接单，不能完成',
}
